language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"

env:
  - DJANGO=">= 1.2, < 1.3"
  - DJANGO=">= 1.3, < 1.4"
  - DJANGO=">= 1.4, < 1.5"
  - DJANGO=">= 1.5, < 1.6"
  - DJANGO=""

matrix:
    include:
        - python: "2.7"
          env: DJANGO=">= 1.5, < 1.6" OLD_WEBTEST=1
    exclude:
        - python: "3.2"
          env: DJANGO=">= 1.2, < 1.3"
        - python: "3.2"
          env: DJANGO=">= 1.3, < 1.4"
        - python: "3.2"
          env: DJANGO=">= 1.4, < 1.5"
        - python: "3.3"
          env: DJANGO=">= 1.2, < 1.3"
        - python: "3.3"
          env: DJANGO=">= 1.3, < 1.4"
        - python: "3.3"
          env: DJANGO=">= 1.4, < 1.5"
        - python: "pypy"
          env: DJANGO=">= 1.2, < 1.3"
        - python: "pypy"
          env: DJANGO=">= 1.3, < 1.4"


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install "django $DJANGO"
  - if [[ $OLD_WEBTEST ]]; then pip install 'WebTest < 2.0'; else pip install WebTest; fi
  - python setup.py install

# command to run tests, e.g. python setup.py test
script: python django_webtest_tests/runtests.py
